name: Use Send Payload Action to Pytest Testmon

on:
  push:
    branches:
      - 'main'

jobs:
  test-and-send-dispatch:
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Send Payload to Test Multi OS
        uses: 7rikazhexde/repo-dispatch-event-sender@main
        with:
          repository_name: '7rikazhexde/repo-dispatch-event-sender'
          event_type: 'test_multi_os'
          ghpages_branch: 'ghpages'  # 省略可能
          os_list: 'ubuntu-latest macos-latest windows-latest'
          python_versions: '3.11 3.12'
          custom_param: 'custom_param_test_val'  # 省略可能
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
